In [2]:
def symbol_table(lines):
    table = {}
    for line in lines:
        lhs, rhs = line.split(' -> ')
        table[rhs] = lhs

    return table

In [3]:
with open('/Users/rmartz/code/mine/paoc/python/aoc/y15/data/day07.txt', 'r') as ifile:
    lines = [l.strip() for l in ifile.readlines()]

In [5]:
stable = symbol_table(lines)
stable

{'x': '123',
 'y': '456',
 'd': 'x AND y',
 'e': 'x OR y',
 'f': 'x LSHIFT 2',
 'g': 'y RSHIFT 2',
 'h': 'NOT x',
 'i': 'NOT y'}

In [ ]:
'NOT A'.replace('NOT ', '')

In [42]:
def charge(wire, wire_values) -> int:
    
    if wire.isnumeric():
        return int(wire) 
    
    rhs = wire_values[wire]
    print(f'{wire} -> {rhs}')
    
    if isinstance(rhs, int):
        wire_values[wire] = rhs
        return wire_values[wire]
    elif ' ' not in rhs:
        res = charge(rhs, wire_values)
        wire_values[wire] = res
        return res
    elif rhs.startswith('NOT'):
        res = ~charge(rhs.replace('NOT ', ''), wire_values) & 0xffff
        wire_values[wire] = res
        return res 
    elif 'AND' in rhs:
        l, r = rhs.split(' AND ')
        res = charge(l, wire_values) & charge(r, wire_values)
        wire_values[wire] = res
        return res 
    elif 'OR' in rhs:
        l, r = rhs.split(' OR ')
        res = charge(l, wire_values) | charge(r, wire_values)
        wire_values[wire] = res
        return res 
    elif 'LSHIFT' in rhs:
        l, r = rhs.split(' LSHIFT ')
        res = charge(l, wire_values) << charge(r, wire_values)
        wire_values[wire] = res
        return res 
    elif 'RSHIFT' in rhs:
        l, r = rhs.split(' RSHIFT ')
        res = charge(l, wire_values) >> charge(r, wire_values)
        wire_values[wire] = res
        return res 

In [39]:
charge('g', stable)
print(stable)

print(456 >> 2)

g -> 1824
{'x': 123, 'y': 456, 'd': 72, 'e': 507, 'f': 492, 'g': 1824, 'h': -124, 'i': -457}
114


## 16-bit integers

The problem for Day 7 called for 16-bit integers. My initial solution was incorrect because the values of bitwise compliment operations (the `NOT` instructions from the problem). 

For example, in the problem instructions, it said that the charge on wire `i` should be the result of `NOT y`. `y`'s value was 456, and the final result of `i` as given was `65079` In the problem description. 

One answer I found online said performing a bitwise `AND` with the value `0xffff` (the max 16 bit value) would result in the correct answer.

Here's how Python represents `~456` in binary: 

In [54]:
bin(-457)

'-0b111001001'

In Python, integers do not have a fixed number of bits. In this case, it represents `-457` as a 9 bit integer. So the task here is to convert the 9-bit representation of `-457` to a 16-bit number. We can use the bitwise `&` operator to do this by doing an `&` operation with the max 16-bit value of `0xffff`. The `-457` will be padded with 0s to 16 bits. Since the `&` operation will only result in a `1` bit if _both_ numbers have a `1` in that position, the resulting value the 16-bit representation of the original value (`-457`) 

In [63]:
res = -0b0000000111001000 & 0b1111111111111111
res

65080

In [57]:
bin(res)

'0b1111111000111000'